### ISSUE TITLE
Alter cases.case_citations table to fix required params

### ISSUE THREAD

**Issue by tehnools** [openlawnz/openlawnz-api#23]
## Tasks
- [x] Remove Primary Key  
- [x] Add unique constraint for case_id  
- [x] Add unique constraint for citation  
- [x] Test local postgraphile API if you can query either caseCitations(citation) or  caseCitations(caseId) seperately
- [x] Send Noel the postgresql changes

## Reason why it's a problem:
If you make case_id and citation a composite primary key. 

Postgraphile's resolvers will assume that to query a caseCitation you need both case_id and citation to select a single caseCitation

**Comment by mcqueen1987** [comment]
After test we found that, the existing local postgraphile API can query both caseCitations(citation) and caseCitations(caseId) seperately. sql like:
query MyQuery {
  caseCitations(
    condition: {
    	citation: "[2018] NZCA 605"
    }
  ) {
    caseId
    citation
  }
}
So, FE could get all citation info through the existing APIs. And after confirmed with @noelsoong, we think we should not change anything in this issue just close it.
